In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv('C:/Users/asus/OneDrive/Desktop/Machine learning/Sakshi Gurule (Data Science)/Dataset .csv')
head=df.head() # in this I have cheked for the first 5 rows of the dataset
col_name=df.columns
print(col_name)
df['Restaurant_Name_Length'] = df['Restaurant Name'].str.len() # in this we have convet text into numerical valuse 
df['Address_Length'] = df['Address'].str.len()
df['Has_Table_Booking_Encoded'] = df['Has Table booking'].map({'Yes': 1, 'No': 0}) # in this i have converted text values in the numerical values
df['Has_Online_Delivery_Encoded'] = df['Has Online delivery'].map({'Yes': 1, 'No': 0})
df[['Has Table booking', 'Has_Table_Booking_Encoded',
    'Has Online delivery', 'Has_Online_Delivery_Encoded']].head() # in this  we have converted into the table format and checked for the changed values
df[['Restaurant_Name_Length', 'Address_Length']].describe()
#Build a regression model to predict the aggregate rating of a restaurant based on available features.
#Split the dataset into training and testing sets and evaluate the model's performance using appropriate metrics.
#Experiment with different algorithms (e.g.,linear regression, decision trees, random forest) and compare their performance.

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')


Restaurant_Name_Length  Address_Length
count             9551.000000     9551.000000
mean                15.164171       53.536698
std                  6.858392       17.122035
min                  2.000000       13.000000
25%                 10.000000       41.000000
50%                 14.000000       52.000000
75%                 19.000000       64.000000
max                 54.000000      132.000000

In [24]:
# in this cell   i will take featues make data frame of evrything so that i can use it it combine gor training and testing purpose
features=[
    'Price range',
    'Votes',
    'Average Cost for two',
    'Longitude',
    'Latitude',
    'Restaurant_Name_Length',
    'Address_Length',
    'Has_Table_Booking_Encoded',
    'Has_Online_Delivery_Encoded'
] # here i have made a dataframe of all the features we are going to use and all the values are numerical because ML Model can't understand RAW text
X=df[features]
y=df['Aggregate rating']
 #Step 3 IN this we will train and test model acoording to industry Standards (80% Train and 20% Test)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
# print(X_train,X_test,y_train,y_test)

In [25]:
# In this we will train required  Models
#Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
print(lr_pred)

# Decision Tree Regressor
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
print(dt_pred)

# Random Forest Regressor

rf = RandomForestRegressor(random_state=42, n_estimators=100)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
print(rf_pred)




[1.89646869 3.21758594 2.50994488 ... 2.55154821 3.25495883 4.20982007]
[3.7 2.2 2.6 ... 3.  3.9 3.6]
[3.31  3.068 2.899 ... 3.044 4.337 4.219]


In [ ]:
# Evaluate the model  as per to get the correct predictions mean_absolute_error, mean_squared_error, r2_score by using these crirterias

def evaluate_model(name, y_test, y_pred):
    print(f"{name} Performance:")
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
    print("R2 Score:", r2_score(y_test, y_pred))
    print("-" * 40)
evaluate_model("Linear Regression", y_test, lr_pred)
evaluate_model("Decision Tree", y_test, dt_pred)
evaluate_model("Random Forest", y_test, rf_pred)
# From the output as we can see that the For the linear Regression Model it is showing the better perfomance than the other models so we cane prefre the linear Regression model for the predictions
 

Linear Regression Performance:
MAE: 1.0668254178819172
RMSE: 1.2854807751119761
R2 Score: 0.2739974973879433
----------------------------------------
Decision Tree Performance:
MAE: 0.2841967556253271
RMSE: 0.4419226818395138
R2 Score: 0.9141975812425074
----------------------------------------
Random Forest Performance:
MAE: 0.19941182626896914
RMSE: 0.30250200167135305
R2 Score: 0.9597965381250337
----------------------------------------
